"""Emit a deterministic, evidence-carrying workspace router (CLAUDE.md / AGENTS.md).

Derived from the dependency graph and the docs atlas; re-runnable, never hand-edited.
This replaces the index.md + read-first + brief that developers maintain by hand: a
model opening the workspace reads one map that says where things live, what is an entry
point, what is the core, and which docs describe what. Every line traces to a graph fact.
"""
from __future__ import annotations


def render_router(pack: dict) -> str:
    relations = [r for r in pack.get("relations", []) if not r.get("external")]
    roles = pack.get("roles", {})
    repos = sorted(r["name"] for r in pack.get("repos", []))
    deps_out: dict[str, set[str]] = {}
    deps_in: dict[str, set[str]] = {}
    for r in relations:
        frm, to = r.get("from"), r.get("to")
        if to:
            deps_out.setdefault(frm, set()).add(to)
            deps_in.setdefault(to, set()).add(frm)

    L = ["# Workspace map", "",
         "Generated by `index` from evidence. Re-run `index router --root .` to refresh; "
         "do not hand-edit.", ""]

    entry = [n for n in repos if "entrypoint" in roles.get(n, [])]
    if entry:
        L.append("## Entry points")
        for n in entry:
            out = ", ".join(sorted(deps_out.get(n, []))) or "nothing internal"
            L.append(f"- `{n}` starts here; depends on {out}")
        L.append("")

    hubs = [n for n in repos if "hub" in roles.get(n, [])]
    if hubs:
        L.append("## Core (most depended-on, change with care)")
        for n in hubs:
            used = ", ".join(sorted(deps_in.get(n, []))) or "nothing"
            L.append(f"- `{n}` is used by {used}")
        L.append("")

    L.append("## Where things live")
    for n in repos:
        rs = ", ".join(roles.get(n, [])) or "unclassified"
        out = sorted(deps_out.get(n, []))
        dep = f"; depends on {', '.join(out)}" if out else ""
        L.append(f"- `{n}` ({rs}){dep}")
    L.append("")

    describes = sorted((e["from"], e["to"]) for e in pack.get("knowledge_edges", [])
                       if e.get("type") == "describes")
    if describes:
        L.append("## Docs")
        for doc, repo in describes:
            L.append(f"- `{doc}` describes `{repo}`")
        L.append("")

    return "\n".join(L).rstrip() + "\n"
